[build]
  command = "npm run build"
  publish = "dist/web/browser"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "supabaseAnonKey,supabaseUrl"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
